### PR TITLE
host adjustment in Client constructor for protocols http & https

### PR DESCRIPTION
**Pull request by mysiar**
changes in constructor to accomodate http & https protocols for client creation.
Please check websocket part. I did it similar but I do not have experience with socket and I'm not sure if it is correct.

Next step: I will reformat all code to accommodate standard JS formating with 2 spaces as tab, etc.

Let me know if you are willing to accept all these changes.

### CODE REVIEW

**Comment by mysiar** [comment]
added code reformat

**Comment by alandoherty** [comment]
Ready to merge except can you remove dependency on ES6 (use of const throughout commits).

**Comment by mysiar** [comment]
the only const that has left was in constructor - it is gone, not sure how to remove them from first commits, as this code has been removed

**Comment by alandoherty** [comment]
Merged, thanks for the help.

**Pull request merged**
